# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata

PROJECT_ROOT = Path(SPECPATH)
sys.path.insert(0, str(PROJECT_ROOT / "src"))
from stereo_selector import DISTRIBUTION_NAME, __version__ as PROJECT_VERSION, release_version  # noqa: E402

RELEASE_VERSION = release_version(PROJECT_VERSION)
APP_NAME = f"StereoSelector-v{RELEASE_VERSION}"
IS_WINDOWS = sys.platform == "win32"
IS_MACOS = sys.platform == "darwin"
if IS_WINDOWS:
    # Keep unrelated command-line toolchains out of DLL dependency discovery.
    # In particular, Poppler's icuuc.dll is not Windows' ICU implementation.
    windows_root = Path(os.environ.get("SystemRoot", "C:/Windows"))
    os.environ["PATH"] = os.pathsep.join(
        str(path) for path in (
            Path(sys.prefix), Path(sys.prefix) / "Scripts", Path(sys.base_prefix),
            windows_root / "System32", windows_root,
        )
    )
DEFAULT_ICON = PROJECT_ROOT / "src" / "stereo_selector" / "assets" / "app_icon.png"
ICON_PATH = os.environ.get("STEREO_SELECTOR_ICON", str(DEFAULT_ICON))
BUILD_DIR = PROJECT_ROOT / "build"
BUILD_DIR.mkdir(exist_ok=True)

hiddenimports = collect_submodules("pyqtgraph.opengl")
# The assets folder carries the icon and the built-in calibration presets.
# Distribution metadata lets the frozen app report the same version string.
datas = collect_data_files("pyqtgraph") + copy_metadata(DISTRIBUTION_NAME) + [
    (str(PROJECT_ROOT / "src" / "stereo_selector" / "assets"), "stereo_selector/assets"),
]


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = []
    for piece in version.split("."):
        digits = "".join(ch for ch in piece if ch.isdigit())
        parts.append(int(digits) if digits else 0)
    parts = (parts + [0, 0, 0, 0])[:4]
    return tuple(parts)


def _write_windows_version_info() -> Path:
    """Generate version_info.txt from pyproject.toml so the two never diverge."""
    major, minor, patch, build = _version_tuple(PROJECT_VERSION)
    text = f'''# UTF-8
# Generated by StereoSelector.spec from pyproject.toml; do not edit by hand.
VSVersionInfo(
    ffi=FixedFileInfo(
        filevers=({major}, {minor}, {patch}, {build}),
        prodvers=({major}, {minor}, {patch}, {build}),
        mask=0x3F,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    "040904B0",
                    [
                        StringStruct("CompanyName", "ToolBox"),
                        StringStruct("FileDescription", "Stereo image, depth and point-cloud inspection workbench"),
                        StringStruct("FileVersion", "{major}.{minor}.{patch}.{build}"),
                        StringStruct("InternalName", "StereoSelector"),
                        StringStruct("OriginalFilename", "{APP_NAME}.exe"),
                        StringStruct("ProductName", "Stereo Selector"),
                        StringStruct("ProductVersion", "{PROJECT_VERSION}"),
                    ],
                )
            ]
        ),
        VarFileInfo([VarStruct("Translation", [1033, 1200])]),
    ],
)
'''
    target = BUILD_DIR / "version_info.txt"
    target.write_text(text, encoding="utf-8")
    return target


a = Analysis(
    [str(PROJECT_ROOT / "main.py")],
    pathex=[str(PROJECT_ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter"],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

# The bootloader loads the root VC runtime before Qt. Older Python installs
# can otherwise shadow Qt's newer runtime and make QtCore fail to import.
if IS_WINDOWS:
    import pefile

    # Windows 10+ provides UCRT and API sets. Never bundle old compatibility
    # copies found on PATH (for example in an unrelated image toolkit).
    a.binaries = [
        entry for entry in a.binaries
        if Path(entry[0]).name.lower() != "ucrtbase.dll"
        and not Path(entry[0]).name.lower().startswith(("api-ms-win-", "ext-ms-win-"))
    ]
    for runtime in ("vcruntime140.dll", "vcruntime140_1.dll", "msvcp140.dll"):
        candidates = []
        for destination, source, _kind in a.binaries:
            if Path(destination).name.lower() == runtime:
                with pefile.PE(source, fast_load=True) as pe:
                    pe.parse_data_directories(directories=[2])
                    info = pe.VS_FIXEDFILEINFO[0]
                    candidates.append(((info.FileVersionMS, info.FileVersionLS), source))
        if candidates:
            source = max(candidates)[1]
            a.binaries = [entry for entry in a.binaries if Path(entry[0]).name.lower() != runtime]
            a.binaries.append((runtime, source, "BINARY"))

exe_options = {
    "name": APP_NAME,
    "debug": False,
    "bootloader_ignore_signals": False,
    "strip": False,
    "upx": IS_WINDOWS,
    "console": False,
    "disable_windowed_traceback": False,
    "argv_emulation": False,
    "target_arch": None,
    "codesign_identity": None,
    "entitlements_file": None,
    "icon": ICON_PATH,
}

if IS_WINDOWS:
    exe_options["version"] = str(_write_windows_version_info())

if IS_MACOS:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        **exe_options,
    )
    collected = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        name=APP_NAME,
    )
    app = BUNDLE(
        collected,
        name=f"{APP_NAME}.app",
        icon=ICON_PATH,
        bundle_identifier="com.toolbox.stereoselector",
        info_plist={
            "CFBundleDisplayName": "Stereo Selector",
            "CFBundleShortVersionString": PROJECT_VERSION,
            "CFBundleVersion": PROJECT_VERSION,
            "NSHighResolutionCapable": True,
        },
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        **exe_options,
    )
