"""Central UI metrics so layout sizes stay consistent across modules.

Replace inline magic numbers in the UI code with these named constants.
"""

WINDOW_DEFAULT_WIDTH = 1520
WINDOW_DEFAULT_HEIGHT = 920
WINDOW_MIN_WIDTH = 1050
WINDOW_MIN_HEIGHT = 680

TITLE_BAR_HEIGHT = 40
INSPECTION_BAR_HEIGHT = 38
INSPECTION_BAR_CURSOR_HEIGHT = 68
CURSOR_INFO_ROW_HEIGHT = 30
CURSOR_INFO_WIDTH = 620

ACTIVITY_BAR_WIDTH = 39

SIDEBAR_EXPANDED_WIDTH = 252
SIDEBAR_MIN_WIDTH = 220
SIDEBAR_MAX_WIDTH = 360

INSPECTOR_MIN_WIDTH = 268
INSPECTOR_MAX_WIDTH = 380

MEDIA_MARGIN = 8
MEDIA_SPACING = 8
MEDIA_COMPACT_MARGIN = 0
MEDIA_COMPACT_SPACING = 1

TILE_MIN_WIDTH = 280
TILE_MIN_HEIGHT = 210

PREVIEW_MAX_DIMENSION = 2048

SPLITTER_SIDEBAR_WIDTH = 40
SPLITTER_WORKSPACE_WIDTH = 1480
SPLITTER_INSPECTOR_WIDTH = 0

ICON_TOOL_SIZE = 28
ICON_ACTIVITY_SIZE = 36
ICON_PANE_SIZE = 32
ICON_PLAYBACK_SIZE = 30
ICON_SPINNER_SIZE = 28
ICON_WINDOW_WIDTH = 42
ICON_WINDOW_HEIGHT = 32
